services:
  api-gateway:
    build: .
    image: taohans/gestaocerta:api-gateway
    container_name: api-gateway
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - gestaocerta-public
      - gestaocerta-private

networks:
  gestaocerta-public:
    driver: bridge
  gestaocerta-private:
    external: true

